CREATE TABLE DEVICE(
DEV_ID BIGSERIAL PRIMARY KEY,
DEV_NAME VARCHAR(255),
);

CREATE TABLE ATTRIBUTE(
ATTR_ID BIGSERIAL PRIMARY KEY,
DEV_ID BIGINT,
ATTR_NAME VARCHAR(255),
ATTR_VALUE_TYPE VARCHAR(255),
FOREIGN KEY (DEV_ID) REFERENCES DEVICE(DEV_ID)
);

CREATE TABLE ATTRIBUTE_VALUE(
ATTR_VALUE_ID BIGSERIAL PRIMARY KEY,
ATTR_ID BIGINT,
ATTR_VALUE VARCHAR(255),
ATTR_VALUE_TIMESTAMP TIMESTAMP,
FOREIGN KEY (ATTR_ID) REFERENCES ATTRIBUTE(ATTR_ID)
);
